### ISSUE TITLE
Ability to teleport to another world without having to install Multiverse or any world teleportation helpers

### ISSUE THREAD

**Issue by johnb165** [TigerHix/Mine-Fortress#12]

**Comment by TigerHix** [comment]
o.0 This is strange, when would you need that feature?

If you are setting up an arena, you should be setting develop-mode to true and set the level-name to your arena world. Teleportation is not needed.

**Comment by johnb165** [comment]
Hmmm... so it only supports one are a? What if I want to add another one..?

**Comment by johnb165** [comment]
Where it says, "are a" it's supposed to be arena.

**Comment by TigerHix** [comment]
You can surely add another one. Just drop in a folder of the new world, setup server.properties to let the server launch that world, ensure develop-mode is set to true, and you can now set up another arena.

When done, simply edit maps.yml to append the list. Set develop-mode back to false, and now Mine Fortress will automatically rotate the arena according to the order of the list :) The same applies to the 3rd, 4th or as many as you want.

**Comment by johnb165** [comment]
Ah, okay. Thanks. <3
