### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by Astelyas** [TigerHix/Mine-Fortress#14]
Hi ! ( sorry i'm french )

I installed MineFortress Plugins with all th others ( WorldEdit, EffectLib, LibsDisguise, ProtocolLib and HolographicDisplays ) 
I restarted my server, i entered the following command:
 "/wizard new"

But after that, when i use "/wizard" it doesn't work:
![problem](https://cloud.githubusercontent.com/assets/20630293/17278960/33f2cd18-5769-11e6-9cdf-602a42cc0e11.png)

Please, if someone can help me...

**Comment by TigerHix** [comment]
Um... as it says, you need to hover the text - using your mouse - to see further instructions.

**Comment by Astelyas** [comment]
Nop, normally, there's a list of settings for  the map... Like in the tutorial vidéo... But i resolved my problem i changed the version of my server, it was in 1.9 and i changed it to 1.9.4.
